name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AZURE_WEBAPP_NAME: reactivities-lc
  NETCORE_VERSION: "3.1.101"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.18.3"

      - name: Client build
        run: cd client-app && npm ci && npm run build && cd ..

      - name: Install dependencies .net
        run: dotnet restore

      - name: Build .net
        run: dotnet build --configuration Release --no-restore

      - name: Test .net
        run: dotnet test --no-restore --verbosity normal

      - name: Publish .net
        run: dotnet publish -c Release -o publish --self-contained false Reactivities.sln
