name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AZURE_WEBAPP_NAME: reactivities-lc
  NETCORE_VERSION: "5.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.18.3"

      - name: Client build
        run: cd client-app && npm ci && npm run build && cd ..

      - name: Install dependencies .net
        run: dotnet restore

      - name: Build .net
        run: dotnet build --configuration Release --no-restore

      - name: Test .net
        run: dotnet test --no-restore --verbosity normal

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "reactivities-lc"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_4a0eaabedae14f209d059eca9b4648ff }}
          package: ${{env.DOTNET_ROOT}}/myapp
